### ISSUE TITLE
Banners on README are broken

### ISSUE THREAD

**Issue by yutannihilation** [electro-smith/DaisySP#100]
After https://github.com/electro-smith/DaisySP/commit/fc89ff549c08cc5482b5ce701fe42e80dfd106a9, README looks like this. Maybe `andrewikenberry/badges` is a private repository?

![image](https://user-images.githubusercontent.com/1978793/103773910-1e026f00-506f-11eb-94b5-c23ba6001e6a.png)

**Comment by andrewikenberry** [comment]
Thanks for pointing that out!

I just opened a PR that fixes this.
