### ISSUE TITLE
Emscripten support

### ISSUE THREAD

**Issue by antisvin** [electro-smith/DaisySP#142]
I've tried building DaisySP based code with emscripten. There was 1 error (not really an error, but some limitation with emcc not understanding a particular combination of access to enum via template object pointer?) and a few warnings related to implicit int/float convertion.

Having fixed that in https://github.com/electro-smith/DaisySP/pull/141, compiled result runs in the browser.

**Comment by stephenhensley** [comment]
closing because #141 is merged.
