### ISSUE TITLE
ADSR produces small step and audible click in decay or release phase

### ISSUE THREAD

**Issue by sdiedrichsen** [electro-smith/DaisySP#154]
https://es-daisy.slack.com/archives/CU7QB1K5Y/p1620032978070300

There's a rather unfortunate comparison, which forces the output to zero once the envelope falls below 0.01.

I'd suggest using a negative target value for the the filter and clip the output at zero. Also, for the attack a target value > 1.0 produces a more pleasant attack phase.

**Comment by jasonmayo** [comment]
There are situations where it would be useful to set ADSR_SEG_IDLE at a given level, such as prioritising voices for polyphonic voice assignment. Could the current 0.01 be a default that can be overridden?
`if(out <= idle_threshold)`

**Comment by sdiedrichsen** [comment]
I'd tend to disagree a bit, the ADSR should produce a clean envelope primarily. But for voice allocation or stealing a accessor method for the segment might be useful.

**Comment by sdiedrichsen** [comment]
OK, here's my remake:
https://github.com/electro-smith/DaisySP/pull/160

**Comment by sdiedrichsen** [comment]
This has been merged, so this issue can be closed now.
