### ISSUE TITLE
std::sin usage in Looper

### ISSUE THREAD

**Issue by antisvin** [electro-smith/DaisySP#169]
I've ran into an issue with the latest library version due to std::sin being used to [define a constant in Looper.h](https://github.com/electro-smith/DaisySP/blob/master/Source/Utility/looper.h#L226) . The problem is that on OWL we replace sin/sinf with calls to arm_sin_f32 from CMSIS by overriding it with a macro. This won't work when it's used from std namespace and it can't be constexpr because of this optimization.

Would it be possible to either use the actual value of 0.7071067811865476  for looper or move it to dsp.h to allow overriding in third party code?

**Comment by stephenhensley** [comment]
Yup! Easy enough; thanks for the feedback!

**Comment by antisvin** [comment]
Thanks, this should do the trick.

**Comment by stephenhensley** [comment]
no problem!
