### ISSUE TITLE
typo in fastroot() ?

### ISSUE THREAD

**Issue by v7b1** [electro-smith/DaisySP#190]
line 83 in dsp.h reads:
`l >>= (n = 1);`
but should probably be:
`l >>= (n - 1);`

**Comment by takumi-ogata** [comment]
Hello v7b1, 

That is indeed a typo. We'll fix it as soon as we can.
Thank you so much for bringing this to our attention.

**Comment by v7b1** [comment]
Great, thanks!

**Comment by beserge** [comment]
Fixed via #191
