### ISSUE TITLE
Module subfolders

### ISSUE THREAD

**Issue by TheSlowGrowth** [electro-smith/DaisySP#28]
A suggestion: Move modules into subfolders to make them easier to find.
I would assume that this library can grow rather quickly and it might be a good idea to organize things from the start.
Subfolders could include:

- modulators
- soundsources
- utilities
- filters
- fx
- ... more?

**Comment by stephenhensley** [comment]
I like this idea. I think it's still small enough that this isn't entirely necessary yet.

However, as you said, this library could grow quite quickly, and at that point something like this would really help finding the things you're looking for.

**Comment by TheSlowGrowth** [comment]
Yes that was exactly my thought. Right now, things are still small enough that such a change wouldn't hurt too much. Should I make a pull request and suggest a folder structure?

**Comment by stephenhensley** [comment]
@TheSlowGrowth Sure! That sounds great.

**Comment by andrewikenberry** [comment]
Initial Folder Outline:

- Filters
- Effects
- Synthesis
- Physical Modeling
- Utility
- Dynamics
- Noise
- Drum
- Control
