### ISSUE TITLE
Consider -Werror

### ISSUE THREAD

**Issue by TheSlowGrowth** [electro-smith/DaisySP#33]
Being a relatively new code base, we could think about including `-Werror` in the compiler options. This would help a lot to keep the compilation output clean and also help find bugs quickly.

**Comment by stephenhensley** [comment]
Yeah, I agree. I personally hate letting warnings slip through.

I think I originally had a shared makefile for this and the libdaisy repo, and didn't know about `-Wno-error=<warning>` for some of the stm32 HAL warnings that we won't be fixing.

But for this repo -Werror would be preferred.
