### ISSUE TITLE
Doc Deployment is failing

### ISSUE THREAD

**Issue by stephenhensley** [electro-smith/DaisySP#43]
There are a few warnings that I don't see when building the docs on my end, but what's weird is it worked before we added the conditional.

I think its the lack of skip cleanup as it is running `git stash --all` before deploying.

**Comment by TheSlowGrowth** [comment]
I had removed it due to warnings in the Travis GUI. It told me that this command is ignored or something like that. Oops.

**Comment by stephenhensley** [comment]
@TheSlowGrowth yeah, I saw the same warning, but weirdly without it the build output still suggests using it.

the warning seems to suggest using `cleanup` instead. I can look into this a bit more later on.

**Comment by stephenhensley** [comment]
doc deployment is succeeding. I'm going to set up CI for libdaisy and daisy examples later this week. So I'll revisit the `cleanup` vs `skip_cleanup` stuff while I'm doing that.
