### ISSUE TITLE
AdEnv - Changing Attack/Decay time during stages can cause envelope to exceed its given range.

### ISSUE THREAD

**Issue by stephenhensley** [electro-smith/DaisySP#50]
With knobs mapped to attack/decay respectively, changing one quickly will some times cause the envelope to go much higher than the values set. 

I haven't checked to see if it happens when curve is set to 0 (linear), but worth investigating.

----

Temporary band-aid, change attack/decay times on re-trigger of the envelope instead of at a constant rate.

**Comment by beserge** [comment]
Fix pending via #54

**Comment by beserge** [comment]
fixed via #54

**Comment by stephenhensley** [comment]
closing as fixed, and I didn't have any issues with the Patch Envelope example
