### ISSUE TITLE
Add some audio-input based examples for some of the effects processors

### ISSUE THREAD

**Issue by stephenhensley** [electro-smith/DaisySP#65]
PitchShift, and ReverbSc come to mind.

As mentioned in #60 there's no harm in having more working examples, and it would be nice to be able to have some examples that use the audio inputs (as long as there is already a working example that doesn't require them already).

**Comment by andrewikenberry** [comment]
closing for now - this is a little too broad, and we are planning our future examples with specific use cases in mind
