### ISSUE TITLE
Tiny documentation error

### ISSUE THREAD

**Issue by StaffanMelin** [electro-smith/DaisySP#91]
In

https://github.com/electro-smith/DaisySP/blob/master/modules/adsr.h

there is a small typo on line 40:

`    /** Initializes the ATone module.`

Should be

`    /** Initializes the Adsr module.`

Was a bit confusing as it is the base for the documentation! :)

**Comment by andrewikenberry** [comment]
Thanks for catching this!

Just made a PR to fix it.
